// pages/index.tsx

import styles from './index.module.scss';

import { useEffect, useState } from 'react';
import { AnimatePresence } from 'framer-motion';

import Preloader from '../components/Preloader';
import Landing from '../components/Landing';
import Projects from '../components/Projects';
import Description from '../components/Description';
import SlidingImages from '../components/SlidingImages';
import Contact from '../components/Contact';
import Head from 'next/head';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let locomotiveScroll: LocomotiveScroll | null = null;

    (async () => {
      const LocomotiveScroll = (await import('locomotive-scroll')).default;

      // Select the scroll container element
      const scrollContainer = document.querySelector(
        '#scroll-container'
      ) as HTMLElement;

      if (scrollContainer) {
        locomotiveScroll = new LocomotiveScroll({
          el: scrollContainer,
          smooth: true,
          // ... any other options you need
        });

        setTimeout(() => {
          setIsLoading(false);
          document.body.style.cursor = 'default';
          window.scrollTo(0, 0);
        }, 2000);
      } else {
        console.error('Scroll container element not found');
      }
    })();

    // Clean up on component unmount
    return () => {
      if (locomotiveScroll) {
        locomotiveScroll.destroy();
      }
    };
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio GSAP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main id="scroll-container" className={styles.main}>
        <AnimatePresence mode="wait">
          {isLoading && <Preloader />}
        </AnimatePresence>
        <Landing />
        <Description />
        <Projects />
        <SlidingImages />
        <Contact />
      </main>
    </>
  );
}
